baseURL = "http://example.org/"
languageCode = "en-us"
title = "Code for UPSC"



[permalinks]
	blog = "/:filename/"



[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3


[taxonomies]
  category = "categories"
  tag = "tags"


[params]
	dateFormat = "Jan 2, 2006"
	homeText = "Blog for Daily News"	
	
